version: '3.1'

services:
  mongo_replica:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mongo 
    command: 'mongod --config /etc/mongo/replica.yml'
    volumes: 
      - "/etc/localtime:/etc/localtime:ro"
      - ./config/replica.yml:/etc/mongo/replica.yml
      - ./script:/script
      - ./data:/data/db
      - ./backup:/backup
    ports:
      - 27017:27017 
    extra_hosts: 
      - "mongo1: 192.168.0.200" 
      - "mongo2: 192.168.0.201"
      - "mongo3: 192.168.0.202"


